name: Generate Metrics

on:
  schedule:
    - cron: '59 23 * * *'
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, isocalendar
          config_isocalendar: "langs"
          config_isocalendar_duration: 1y
